<a href="https://colab.research.google.com/github/FaizanHassanSiddiqui/MachineLearning/blob/main/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# K Nearest Neighbours



In [3]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [4]:
from google.colab import files
uploaded = files.upload()       # this is for uploading files from your local system

In [5]:
# Download Dataset from this link
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data

--2021-02-06 15:43:17--  https://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51867 (51K) [application/x-httpd-php]
Saving to: ‘car.data’

car.data            100%[===================>]  50.65K  --.-KB/s    in 0.1s    

2021-02-06 15:43:18 (486 KB/s) - ‘car.data’ saved [51867/51867]



In [14]:
df = pd.read_csv('/content/car.data', names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class'] )


In [15]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [30]:
X = df[['buying', 'maint', 'safety']]

In [82]:
y = df['class']

In [32]:
X.shape, y.shape

((1728, 3), (1728,))

In [33]:
X.head()


buying  maint safety
0  vhigh  vhigh    low
1  vhigh  vhigh    med
2  vhigh  vhigh   high
3  vhigh  vhigh    low
4  vhigh  vhigh    med

In [34]:
y.head()

0    unacc
1    unacc
2    unacc
3    unacc
4    unacc
Name: class, dtype: object

In [42]:
X= X.values

In [43]:
# encoding our features' values to numbers so that they can be passed into the model

Le = LabelEncoder()
for i in range(X.shape[1]):
  X[:, i] = Le.fit_transform(X[:, i])

In [46]:
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [86]:
label_mapping = {'unacc' : 0,
                 'acc' : 1,
                 'vgood' : 2,
                 'good' : 3}

y = y.map(label_mapping)

In [88]:
y = np.array(y)

In [90]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [91]:
np.unique(y_train)


array([0, 1, 2, 3])

In [92]:
# create model

knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')

# train model

knn.fit(X_train, y_train)



KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=25, p=2,
                     weights='uniform')

In [94]:
# predict using the trained model

prediction = knn.predict(X_test)

In [97]:
# calculate accuracy on test set

acc = metrics.accuracy_score(y_test, prediction)

print("prections: ", prediction)
print("accuracy: ", acc)

prections:  [0 3 2 0 0 0 0 0 1 2 0 0 0 0 0 0 2 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 2 0 0 0 0
 1 3 0 0 0 0 2 2 0 1 1 0 0 0 0 2 0 1 0 1 0 3 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0
 0 0 3 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 3 1 0 0 0 1 1 0 2 0 0 0 3 0 0 0
 0 1 0 0 1 0 0 0 0 2 0 0 0 0 1 3 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1
 0 0 0 0 0 0 1 0 0 1 0 0 1 3 0 0 1 1 0 0 0 0 2 0 0 0 0 0 0 0 0 1 0 0 3 0 0
 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 1 2 0 0 0 1 0 1 0 0 0 0 1 0 2
 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 3 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 2 1
 1 3 2 0 0 0 0 1 0 0 0 0 0 0 0 0 0 3 0 0 0 1 0 0 1 1 1 1 3 0 0 0 0 0 0 0 0
 0 0 0 0 1 1 2 2 0 0 3 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1
 0 0 1 0 0 0 1 0 0 0 0 0 3]
accuracy:  0.7601156069364162
